### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Andre601** [tipsy/javalin-prometheus-example#1]
Hey there,

I read the tutorial on the javalin page and got a few questions I hope to get answers for.

First one is, if this could be used in combination with a Discord Bot Library, such as JDA, to create a Dashboard that shows the current state of the different shards the bot has (Ping, Server count, connection status, etc) and make it publicly viewable by others.

Next question would be if there is actually a sort of live-demo to view, to get a feel for how it would look like at the end.

Thanks in advance for the answers.

**Comment by tipsy** [comment]
Hi @Andre601! There is nothing "special" about Javalin's integration with Prometheus or Grafana. So yes, you can combine it with anything you want. There is no live demo of the code here, but any live demo of Prometheus or Grafana should be the same, there is nothing Javalin specific in this example.

**Comment by Andre601** [comment]
Okay.
I guess I'll have to look into this further and see what I can do here.
